create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sale_date date not null,
  category text not null,
  subcategory text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0),
  store text not null,
  channel text not null,
  created_at timestamptz not null default now()
);

alter table public.sales enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.sales to anon, authenticated;
grant insert, update, delete on table public.sales to authenticated;
grant usage, select on sequence public.sales_id_seq to authenticated;

drop policy if exists "Public can read sales" on public.sales;
create policy "Public can read sales"
on public.sales for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can insert sales" on public.sales;
create policy "Authenticated users can insert sales"
on public.sales for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update sales" on public.sales;
create policy "Authenticated users can update sales"
on public.sales for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete sales" on public.sales;
create policy "Authenticated users can delete sales"
on public.sales for delete
to authenticated
using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sales'
  ) then
    alter publication supabase_realtime add table public.sales;
  end if;
end
$$;
